# Generated by Django 5.2.17 on 2026-10-01 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_delivery_agent_order_delivery_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash on delivery'), ('upi', 'UPI on delivery')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reference', models.CharField(blank=True, help_text='UPI transaction ID (optional).', max_length=40)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order')),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['collected_by', 'collected_at'], name='payments_pa_collect_5347d5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive')],
            },
        ),
    ]
