# Generated by Django 5.2.17 on 2026-10-01 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address'),
        ('stores', '0002_pune_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Only for Store Staff and Delivery Agents.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team', to='stores.store'),
        ),
    ]
