# Generated by Django 5.2.17 on 2026-10-01 15:37

import django.db.models.deletion
import tagging.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial_catalog'),
        ('orders', '0003_initial_slots_coupons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.CharField(choices=[('pickup', 'At pickup'), ('store', 'At store (tagged)'), ('delivery', 'At delivery')], max_length=10)),
                ('count', models.PositiveSmallIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_checks', to='orders.order')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'recorded_at'],
                'constraints': [models.UniqueConstraint(fields=('order', 'checkpoint'), name='one_count_per_checkpoint')],
            },
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveSmallIntegerField(help_text='1, 2, 3 ... within the order.')),
                ('tag_code', models.CharField(help_text='Printed on the tag, e.g. WO-000012-03.', max_length=20, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('express_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('description', models.CharField(blank=True, help_text="Colour / brand, e.g. 'Blue, Raymond'.", max_length=120)),
                ('has_stain', models.BooleanField(default=False)),
                ('has_damage', models.BooleanField(default=False)),
                ('condition_note', models.CharField(blank=True, help_text="Where and what, e.g. 'Oil stain on left sleeve'.", max_length=300)),
                ('photo', models.ImageField(blank=True, upload_to='garments/%Y/%m/', validators=[tagging.models.validate_photo_size])),
                ('tagged_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.servicecategory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garments', to='orders.order')),
                ('tagged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'seq'],
                'constraints': [models.UniqueConstraint(fields=('order', 'seq'), name='unique_garment_seq_per_order'), models.CheckConstraint(condition=models.Q(models.Q(('has_damage', False), ('has_stain', False)), models.Q(('condition_note', ''), _negated=True), _connector='OR'), name='garment_issue_needs_note', violation_error_message='Please describe the stain or damage.')],
            },
        ),
        migrations.CreateModel(
            name='MismatchAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.CharField(choices=[('pickup', 'At pickup'), ('store', 'At store (tagged)'), ('delivery', 'At delivery')], help_text='Where the difference was found.', max_length=10)),
                ('expected_count', models.PositiveSmallIntegerField(help_text='Count at the previous checkpoint.')),
                ('actual_count', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=300)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mismatch_alerts', to='orders.order')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('expected_count', models.F('actual_count')), _negated=True), name='alert_only_when_counts_differ'), models.CheckConstraint(condition=models.Q(('status', 'open'), ('resolved_at__isnull', False), _connector='OR'), name='resolved_alert_has_time')],
            },
        ),
    ]
