# Generated by Django 5.2.17 on 2026-10-01 09:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('group', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('household', 'Household'), ('footwear', 'Footwear'), ('accessories', 'Accessories')], db_index=True, max_length=20)),
                ('unit', models.CharField(choices=[('piece', 'per piece'), ('pair', 'per pair'), ('set', 'per set')], default='piece', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(help_text='Used in web addresses, e.g. dry-clean.', max_length=60, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='basket', help_text="Bootstrap Icons name, e.g. 'stars'.", max_length=40)),
                ('standard_turnaround_hours', models.PositiveSmallIntegerField(default=48)),
                ('express_available', models.BooleanField(default=False)),
                ('express_surcharge_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Extra % added to the price when the customer chooses Express.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('express_turnaround_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'service categories',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('express_surcharge_percent__gte', 0), ('express_surcharge_percent__lte', 100)), name='category_surcharge_0_to_100'), models.CheckConstraint(condition=models.Q(('express_available', False), models.Q(('express_surcharge_percent__gt', 0), ('express_turnaround_hours__isnull', False)), _connector='OR'), name='category_express_needs_surcharge_and_time', violation_error_message='Express needs a surcharge above 0% and an express turnaround time.')],
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='catalog.servicecategory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='catalog.item')),
            ],
            options={
                'ordering': ['category__sort_order', 'item__sort_order', 'item__name'],
                'constraints': [models.UniqueConstraint(fields=('category', 'item'), name='unique_price_per_category_item'), models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='price_positive')],
            },
        ),
    ]
