from io import BytesIO

import qrcode
import qrcode.image.svg
from django import template
from django.urls import reverse
from django.utils.safestring import mark_safe

register = template.Library()


def qr_svg(data):
    """QR code as an inline <svg> string (vector: sharp on screen and in print, no image files)."""
    img = qrcode.make(data, image_factory=qrcode.image.svg.SvgPathImage, box_size=10, border=1)
    buf = BytesIO()
    img.save(buf)
    svg = buf.getvalue().decode()
    svg = svg[svg.index("<svg"):]  # drop the <?xml ...?> line so it can sit inside HTML
    return svg.replace("<svg ", '<svg class="qr" role="img" ', 1)


@register.simple_tag(takes_context=True)
def garment_qr(context, garment):
    """QR that opens the garment's page when a staff member scans the tag with a phone."""
    url = context["request"].build_absolute_uri(reverse("tagging:garment_lookup", args=[garment.tag_code]))
    return mark_safe(qr_svg(url))  # safe: generated by the qrcode library from our own URL
