# Generated by Django 5.2.17 on 2026-10-01 09:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('state', models.CharField(default='Maharashtra', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('locality', models.CharField(help_text='Area where the store is, e.g. Kothrud.', max_length=100)),
                ('pincode', models.CharField(db_index=True, max_length=6, validators=[django.core.validators.RegexValidator('^[1-9]\\d{5}$', 'Enter a valid 6-digit pincode.')])),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='stores.city')),
            ],
            options={
                'ordering': ['city__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='locality')),
                ('pincode', models.CharField(db_index=True, max_length=6, validators=[django.core.validators.RegexValidator('^[1-9]\\d{5}$', 'Enter a valid 6-digit pincode.')])),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='stores.store')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.CheckConstraint(condition=models.Q(('closing_time__gt', models.F('opening_time'))), name='store_closes_after_opening'),
        ),
        migrations.AddConstraint(
            model_name='servicearea',
            constraint=models.UniqueConstraint(fields=('name', 'pincode'), name='unique_area_name_pincode'),
        ),
    ]
