# Generated by Django 5.2.17 on 2026-10-01 13:30

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.datetime
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_address'),
        ('catalog', '0002_initial_catalog'),
        ('stores', '0002_pune_stores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Customers type this. Stored in CAPITALS.', max_length=20, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('discount_type', models.CharField(choices=[('flat', 'Flat amount (₹)'), ('percent', 'Percentage (%)')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='₹ amount or % depending on type.', max_digits=8)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Upper limit for percentage coupons (optional).', max_digits=8, null=True)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total uses allowed. Empty = unlimited.', null=True)),
                ('per_user_limit', models.PositiveSmallIntegerField(default=1, help_text='Uses per customer. 0 = unlimited.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-valid_until', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='coupon_value_positive'), models.CheckConstraint(condition=models.Q(('discount_type', 'flat'), ('value__lte', 100), _connector='OR'), name='coupon_percent_max_100'), models.CheckConstraint(condition=models.Q(('valid_until__gte', models.F('valid_from'))), name='coupon_dates_in_order'), models.CheckConstraint(condition=models.Q(('code', django.db.models.functions.text.Upper('code'))), name='coupon_code_uppercase')],
            },
        ),
        migrations.CreateModel(
            name='DailySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booked_count', models.PositiveSmallIntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_slots', to='stores.servicearea')),
            ],
            options={
                'ordering': ['date', 'time_slot__start_time'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Order number shown to customers.', max_length=12, null=True, unique=True)),
                ('address_snapshot', models.TextField()),
                ('is_express', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('pickup_assigned', 'Pickup Assigned'), ('picked_up', 'Picked Up'), ('at_store', 'At Store'), ('tagged', 'Tagged'), ('in_cleaning', 'In Cleaning'), ('ready', 'Ready'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='booked', max_length=20)),
                ('estimated_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('express_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_finalised', models.BooleanField(default=False)),
                ('customer_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.address')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('pickup_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.dailyslot')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('express_surcharge', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Extra per unit for Express.', max_digits=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.servicecategory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['category__sort_order', 'item__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, db_default='', max_length=300)),
                ('changed_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'order status history',
                'ordering': ['changed_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['start_time'],
                'constraints': [models.UniqueConstraint(fields=('start_time', 'end_time'), name='unique_time_slot'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='slot_ends_after_start'), models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='slot_capacity_at_least_1')],
            },
        ),
        migrations.AddField(
            model_name='dailyslot',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_slots', to='orders.timeslot'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='orders_orde_custome_413d7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['booked', 'pickup_assigned', 'picked_up', 'at_store', 'tagged', 'in_cleaning', 'ready', 'out_for_delivery', 'delivered', 'cancelled'])), name='order_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0), ('express_charge__gte', 0), ('subtotal__gte', 0), ('total__gte', 0)), name='order_amounts_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal'), '+', models.F('express_charge')), '-', models.F('discount')))), name='order_total_adds_up'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'category', 'item'), name='unique_item_per_order'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_item_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', 'changed_at'], name='orders_orde_order_i_7978aa_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyslot',
            index=models.Index(fields=['date', 'area'], name='orders_dail_date_f9af66_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyslot',
            constraint=models.UniqueConstraint(fields=('date', 'time_slot', 'area'), name='unique_daily_slot'),
        ),
        migrations.AddConstraint(
            model_name='dailyslot',
            constraint=models.CheckConstraint(condition=models.Q(('booked_count__gte', 0)), name='daily_slot_count_not_negative'),
        ),
    ]
